name: CI

on:
  push:
    branches: [develop]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: node_modules
          key: deps-${{ hashFiles('yarn.lock') }}
      - run: yarn install
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: yarn build
      - run: yarn test
